name: Create Release

# This workflow is triggered on push events to the main branch
on:
  workflow_dispatch:

# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'temurin'
        cache: 'maven'    
    - name: Build with Maven
      run:
        mvn  --file pom.xml -B package
    - name: Extract build version
      run: echo "POM_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Create tag
      run: |
        git tag v${{ env.POM_VERSION }}
        git push origin tag v${{ env.POM_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      run: |
        cd ${{github.workspace}}
        gh release create v${{ env.POM_VERSION }} ./target/test-${{ env.POM_VERSION }}.jar --verify-tag --draft --prerelease --title 'Release v${{ env.POM_VERSION }}' --notes-file ./RELEASE.md     
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}